language: java
sudo: required
dist: trusty
group: edge

addons:
  sonarcloud:
    organization: trellis-ldp

before_cache:
  - rm -f $HOME/.gradle/caches/modules-2/modules-2.lock
  - rm -rf $HOME/.gradle/caches/*/plugin-resolution/
  - rm -f  $HOME/.gradle/caches/*/fileHashes/fileHashes.bin
  - rm -f  $HOME/.gradle/caches/*/fileHashes/fileHashes.lock

cache:
  directories:
    - $HOME/.gradle/caches/
    - $HOME/.gradle/wrapper/

stages:
  - test
  - deploy

branches:
  only:
    - master
    # release tags
    - /^trellis-\d+\.\d+\.\d+$/
    # maintenance branches
    - /^trellis-\d+\.\d+\.x$/
    # long-lived branches
    - /branch-.+/

jobs:
  include:
    # JDK 8
    - stage: test
      jdk: oraclejdk8
      script: travis_retry ./gradlew check install jacocoRootReport coveralls sonarqube

    # JDK 11
    - stage: test
      jdk: openjdk11
      script: travis_retry ./gradlew check install

    # deploy JDK 8 builds
    - stage: deploy
      jdk: oraclejdk8
      if: branch = master AND type = push
      script: ./gradlew clean publish

