language: java
sudo: required
dist: trusty
group: edge

addons:
  sonarcloud:
    organization: trellis-ldp
  postgresql: "9.4"

before_cache:
  - rm -f $HOME/.gradle/caches/modules-2/modules-2.lock
  - rm -rf $HOME/.gradle/caches/*/plugin-resolution/
  - rm -f  $HOME/.gradle/caches/*/fileHashes/fileHashes.bin
  - rm -f  $HOME/.gradle/caches/*/fileHashes/fileHashes.lock

cache:
  directories:
    - $HOME/.gradle/caches/
    - $HOME/.gradle/wrapper/

stages:
  - test
  - deploy

services:
  - postgresql

branches:
  only:
    - master
    # release tags
    - /^trellis-\d+\.\d+\.\d+$/
    # maintenance branches
    - /^trellis-\d+\.\d+\.x$/
    # long-lived branches
    - /branch-.+/

before_script:
  - psql -c 'create database trellis;' -U postgres

env:
  - JOB=check

jobs:
  fast_finish: true

  allow_failures:
    - env: JOB=sonatype
    - env: JOB=docker
    - env: JOB=aws

  include:
    # JDK 8
    - name: "Java 8"
      stage: test
      jdk: openjdk8
      env:
        - QUARKUS_DATASOURCE_USERNAME=postgres
        - QUARKUS_DATASOURCE_PASSWORD=postgres
        - QUARKUS_DATASOURCE_JDBC_URL=jdbc:postgresql://localhost/trellis
      script: ./gradlew check install -Ptriplestore jacocoRootReport --scan
      after_success: ./gradlew coveralls sonarqube -Ptriplestore

    # deploy JDK 8 builds to Sonatype
    - name: "Publish to Sonatype"
      stage: deploy
      jdk: openjdk8
      env: JOB=sonatype
      if: branch = master AND type = push
      # Only automate the publication of SNAPSHOTS
      script: if [[ $(./gradlew -q getVersion) == *SNAPSHOT* ]]; then ./gradlew publish ; fi

    # deploy to Docker hub
    - name: "Publish to Docker hub"
      stage: deploy
      jdk: openjdk11
      if: (branch = master OR branch =~ /^trellis-\d+\.\d+\.\d+$/) AND type = push
      env: JOB=docker
      before_script: echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
      script: ./buildtools/src/main/resources/docker/publishToDockerHub.sh

    # deploy to AWS
    - name: "Publish JavaDocs"
      stage: deploy
      jdk: openjdk8
      env: JOB=aws
      if: branch =~ /^trellis-\d+\.\d+\.\d+$/ AND type = push
      script: ./gradlew apidocs
      deploy:
          provider: s3
          access_key_id: $AWS_ACCESS_KEY
          secret_access_key: $AWS_SECRET_KEY
          bucket: $AWS_BUCKET
          skip_cleanup: true
          local_dir: docs/apidocs/$(./gradlew -q getVersion)
          upload-dir: docs/trellis/$(./gradlew -q getVersion)/apidocs
          default_text_charset: 'utf-8'
          on:
              all_branches: true

