server:
  applicationConnectors:
    - type: http
      port: 8080
  requestLog:
    appenders:
      - type: console
        target: stdout
        threshold: INFO
      - type: file
        currentLogFilename: /opt/trellis/log/access.log
        archive: true
        archivedLogFilenamePattern: /opt/trellis/log/access-%i.log
        archivedFileCount: 5
        maxFileSize: 100K

logging:
  level: WARN
  appenders:
    - type: console
      target: stdout
      threshold: INFO
    - type: file
      currentLogFilename: /opt/trellis/log/trellis.log
      archive: true
      archivedLogFilenamePattern: /opt/trellis/log/trellis-%i.log
      archivedFileCount: 5
      maxFileSize: 100K
  loggers:
    org.trellisldp: INFO
    io.dropwizard: INFO

# This may refer to a remote Triplestore, e.g. https://example.org/sparql
resources: ${TRELLIS_RESOURCES:-/opt/trellis/data/rdf}

binaries: ${TRELLIS_BINARIES:-/opt/trellis/data/binaries}

mementos: ${TRELLIS_MEMENTOS:-/opt/trellis/data/mementos}

namespaces: ${TRELLIS_NAMESPACES:-/opt/trellis/data/namespaces.json}

# This may refer to a static base URL for resources. If left empty, the
# base URL will reflect the Host header in the request.
baseUrl: ${TRELLIS_BASE_URL:-}

# This configuration will enable a WebSub "hub" header.
hubUrl: ${TRELLIS_HUB_URL:-}

auth:
    adminUsers: []
    webac:
        enabled: ${TRELLIS_AUTH_WEBAC_ENABLED:-true}
        cacheSize: ${TRELLIS_AUTH_WEBAC_CACHE_SIZE:-1000}
        cacheExpireSeconds: ${TRELLIS_AUTH_WEBAC_CACHE_EXPIRE_SECONDS:-600}
    jwt:
        enabled: ${TRELLIS_AUTH_JWT_ENABLED:-false}
        key: ${TRELLIS_AUTH_JWT_KEY:-}
    basic:
        enabled: ${TRELLIS_AUTH_BASIC_ENABLED:-true}
        usersFile: ${TRELLIS_AUTH_BASIC_USERS_FILE:-/opt/trellis/etc/users.auth}

cors:
    enabled: ${TRELLIS_CORS_ENABLED:-true}
    allowOrigin:
        - "*"
    maxAge: ${TRELLIS_CORS_MAX_AGE:-180}

cache:
    maxAge: ${TRELLIS_CACHE_MAX_AGE:-86400}
    mustRevalidate: ${TRELLIS_CACHE_MUST_REVALIDATE:-true}

notifications:
    enabled: ${TRELLIS_NOTIFICATIONS_ENABLED:-false}
    type: ${TRELLIS_NOTIFICATIONS_TYPE:-JMS}
    topicName: ${TRELLIS_NOTIFICATIONS_TOPIC_NAME:-trellis}
    connectionString: ${TRELLIS_NOTIFICATIONS_CONNECTION_STRING:-tcp://localhost:61616}

# JSON-LD configuration
jsonld:
    cacheSize: ${TRELLIS_JSONLD_CACHE_SIZE:-100}
    cacheExpireHours: ${TRELLIS_JSONLD_CACHE_EXPIRE_HOURS:-24}
    contextWhitelist: []
    contextDomainWhitelist: []

